layouts_dir: 'node_modules/uptick-demo-site/dist'

package_name: React Interactive Tutorials
package_github_url: https://github.com/uptick/react-interactive-tutorials
package_npm_url: https://www.npmjs.com/package/react-interactive-tutorials
